spring:
  application:
    name: exactly-once
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka_patterns
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
outbox:
  relay:
    delay-ms: 1000

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
