spring:
  application:
    name: idempotent-consumer
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka_patterns
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
server:
  port: 8083
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        spring.json.trusted.packages: "*"
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
